name: Pull Request Labeler

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false

      - uses: srvaroa/labeler@0a20eccb8c94a1ee0bed5f16859aece1c45c3e55
        with:
          config_path: .github/labeler.yml
          fail_on_error: true
          use_local_config: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
